name: Deploy to Docker

on:
  push:
    branches:
      - publish
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build .NET application
      run: dotnet publish -c Release -o out

    - name: Archive Docker image
      run: |
        docker build -t shopproject:latest .
        docker save shopproject:latest -o shopproject.tar

    - name: Transfer image to server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: shopproject.tar
        target: /home/${{ secrets.SERVER_USER }}/shopproject.tar

    - name: Deploy on server
      uses:  appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
<<<<<<< HEAD
          docker load -i /home/${{ secrets.SERVER_USER }}/shopproject.tar/shopproject.tar
          docker stop shopproject || true 
          docker rm shopproject || true
          docker run -d --name shopproject -p 8081:8081 -p 8080:8080 shopproject:latest
=======
          
          docker stop shopproject 
          docker rm shopproject
          docker run -d --name shopproject -p 8081:8081 -p 8080:8080 agent2303/shopproject:latest
>>>>>>> 4eb1b5f53b383a12eb5b54a9b52ff9ba92ad7f58
