name: Deploy to Docker

on:
  push:
    branches:
      - publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build .NET application
      run: dotnet publish -c Release -o out

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t agent2303/ShopProduct:latest .
        docker push agent2303/ShopProduct:latest

    - name: Deploy on server
       uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull agent2303/ShopProduct:latest
          docker stop ShopProduct || true
          docker rm ShopProduct || true
          docker run -d --name ShopProduct -p 6969:6969 agent2303/ShopProduct:latest
