name: Deploy to Docker

on:
  push:
    branches:
      - branch-name  publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build .NET application
      run: dotnet publish -c Release -o out

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t itstaheri1@gmail.com/ShopProduct:latest
        docker push itstaheri1@gmail.com/ShopProduct:latest

    - name: Deploy on server
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull your-docker-repo/your-app:latest
          docker stop your-app || true
          docker rm your-app || true
          docker run -d --name your-app -p 8080:80 your-docker-repo/your-app:latest
