name: Deploy to Docker

on:
  push:
    branches:
<<<<<<< HEAD
      - publish
=======
      - branch-name  publish
>>>>>>> a74a5412aeeafa493b7e8d6e55d1e1576756d780

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build .NET application
      run: dotnet publish -c Release -o out

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t agent2303/shopproduct:latest .
        docker push agent2303/shopproduct:latest

    - name: Deploy on server
      uses:  appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull agent2303/shopproduct:latest
          docker stop shopproduct || true
          docker rm shopproduct || true
          docker run -d --name shopproduct -p 6969:6969 agent2303/shopproduct:latest
