name: Dependency Review

on:
  pull_request:
    branches:
      - main

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependency review
      uses: actions/dependency-review-action@v1
